# This file is made by MakerTim, a modded version of Sansko1337
# Last Changed 19-12-2015 00:11
buildfase:
  stage: build
  script:
    - set $(git remote show -n origin | grep Fetch | sed 's%^.*/\([^/]*\)\.git$%\1%g')
    - mvn install
    - mkdir -p ../target
    - cp target/$1.jar ../target/$1.jar
  only:
    - master
distributefase:
  stage: deploy
  script:
# Set variable $1 as the jar name
    - set $(git remote show -n origin | grep Fetch | sed 's%^.*/\([^/]*\)\.git$%\1%g').jar
# Sudo su
    - "echo $gitcipass|sudo -S bash"
# Copy files to there locations
    - "sudo cp -f ../target/$1 /home/minecraft/multicraft/servers/server3/plugins/update"
    - "sudo cp -f ../target/$1 /home/minecraft/multicraft/servers/server5/plugins/update"
    - "sudo cp -f ../target/$1 /home/minecraft/multicraft/servers/server9/plugins/update"
    - "sudo cp -f ../target/$1 /home/minecraft/multicraft/servers/server14/plugins/update"
  only:
    - master
stages:
  - build
  - deploy