# This file is made by MakerTim, a modded version of Sansko1337
# Last Changed 03-03-2016 01:52
buildfase:
  stage: build
  script:
    - mvn clean install
#    - curl -T target/$1.jar ftp://Deploy.3:$ftppass@localhost/plugins/update/
#    - curl -T target/$1.jar ftp://Deploy.5:$ftppass@localhost/plugins/update/
#    - curl -T target/$1.jar ftp://Deploy.8:$ftppass@localhost/plugins/update/
#    - curl -T target/$1.jar ftp://Deploy.9:$ftppass@localhost/plugins/update/
#    - curl -T target/$1.jar ftp://Deploy.14:$ftppass@localhost/plugins/update/
#    - curl -T target/$1.jar ftp://Deploy.16:$ftppass@localhost/plugins/update/
#    - curl -T target/$1.jar ftp://Deploy.17:$ftppass@localhost/plugins/update/
stages:
  - build