# This file is made by MakerTim, a modded version of Sansko1337
# Last Changed 29-10-2015 00:11
buildfase:
  stage: build
  script:
# Set variable $1 as the jar name
    - set $(git remote show -n origin | grep Fetch | sed 's%^.*/\([^/]*\)\.git$%\1%g')
# allow use of **
    - shopt -s globstar
# remove old build directory
    - rm -rf build
# create build and dist directory
    - mkdir build
    - mkdir -p ../dist
# set plugin version and plugin name inside plugin.yml
    - "sed -e 's/^name.*$/name: '$1'/g' ./src/plugin.yml > ./src/plugin.yml.temp"
    - mv ./src/plugin.yml.temp ./src/plugin.yml
    - "sed -e 's/^version.*$/version: '$(git rev-parse --short HEAD)'/g' ./src/plugin.yml > ./src/plugin.yml.temp"
    - mv ./src/plugin.yml.temp ./src/plugin.yml
# compile all java files with as classpath everything inside libs directory
    - javac -cp $(find ./libs -regex '.*\.jar' -printf '%p:') -d ./build ./src/**/*.java
# copy all non java files to the build directory
    - (cd ./src; find . -type f ! -regex '.*\.java$' -exec cp '--parents' '{}' '../build' ';') 
# create a .jar file from everything inside the build directory AND put it in the ../dist directory
    - jar cvf ../dist/$1.jar -C ./build/ .
  only:
  - master
distributefase:
  stage: deploy
  script:
# Set variable $1 as the jar name
    - set $(git remote show -n origin | grep Fetch | sed 's%^.*/\([^/]*\)\.git$%\1%g').jar
# Copy files to there locations
    - "echo $gitcipass|sudo -S cp -f ../dist/$1 /home/minecraft/multicraft/servers/server14/plugins/update"
stages:
  - build
  - deploy