name: SoundOfNoteblocks
main: nl.imine.soundofnoteblocks.SoundOfNoteBlocks
version: ${git.commit.id.abbrev}
depend: [NoteBlockAPI, iMineAPI]
commands:
  jukebox:
    description: Main command for musicboxes
    usage: /records reload to reload the track list
    alias: [musicbox, tracklist]